services:
  # https://hub.docker.com/r/itsthenetwork/nfs-server-alpine
  # nfs:
  #   image: openebs/nfs-server-alpine:latest
  #   container_name: nfs
  #   network_mode: host
  #   restart: unless-stopped
  #   privileged: true
  #   environment:
  #     - SHARED_DIRECTORY=/data
  #   volumes:
  #     - /docker:/data
  #   ports:
  #     - 2049:2049

  db:
    image: image: mysql:8.4.0
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD_FILE=/home/docker/secrets/mysql-root
    volumes:
      - type: volume
        source: /home/docker/volumes/mysql
        target: /data
        # volume:
        #   nocopy: true
        #   subpath: sub
