services:
  # https://hub.docker.com/r/itsthenetwork/nfs-server-alpine
  nfs:
    image: openebs/nfs-server-alpine:latest
    container_name: nfs
    network_mode: host
    restart: unless-stopped
    privileged: true
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - /docker:/data
    ports:
      - 2049:2049


