services:  
  db:
    image: mysql:latest
    container_name: db-mysql
    restart: no
    environment:
       - MYSQL_DATABASE=pilabgaming
       - MYSQL_USER=pilabgaming
       - MYSQL_PASSWORD_FILE=/run/secrets/db_password
       - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password_owner
       - MYSQL_TCP_PORT=3306
    secrets:
      - db_password
      - db_password_owner
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306

volumes:
  my-db:

secrets:
  db_password:
    file: /data/compose/1/secrets/db_password.txt
  db_password_owner:
    file: /data/compose/1/secrets/db_password_owner.txt
