services:  
  db:
    image: mysql:latest
    container_name: db-mysql
    # restart: no
    environment:
       - MYSQL_DATABASE=pilabgaming
       - MYSQL_USER=pilabgaming
       - MYSQL_PASSWORD_FILE=/run/secrets/db_password
       - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password_owner
       - MYSQL_TCP_PORT=3306
    secrets:
      - db_password
      - db_password_owner
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306

  kanboard:
    # https://hub.docker.com/r/kanboard/kanboard
    image: kanboard/kanboard:latest
    container_name: kanboard
    # restart: no
    ports:
      - "65080:80"
      - "65443:443"
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
      - kanboard_ssl:/etc/nginx/ssl

volumes:
  kanboard_data:
  kanboard_plugins:
  kanboard_ssl:
  my-db:

secrets:
  db_password:
    file: /data/compose/1/secrets/db_password.txt
  db_password_owner:
    file: /data/compose/1/secrets/db_password_owner.txt
